---
# =============================================================================
# PLAYBOOK ESPECIAL - Configuración remota vía API/Scripts
# =============================================================================

- name: "🚀 Configurar Ubuntu Server desde tu Mac"
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  
  vars:
    ubuntu_target_ip: "172.17.25.48"
    new_ip: "192.168.0.48"
    
  tasks:
    - name: "📋 Información importante"
      debug:
        msg: |
          🎯 Para que Ansible funcione, necesitamos que Ubuntu Server esté en tu red.
          
          📍 Estado actual:
          - Ubuntu Server: {{ ubuntu_target_ip }} (red del laboratorio)  
          - Tu Mac: 192.168.0.170 (red local)
          
          💡 Opciones disponibles:
          1. Cambiar Ubuntu Server a red local (requiere acceso a consola)
          2. Usar VPN/túnel (complejo)
          3. Trabajar directamente desde la red del laboratorio
          
          🎓 Recomendación educativa:
          Conectarte a la misma red que el laboratorio para experiencia real.
          
    - name: "🔍 Verificar conectividad actual"
      command: ping -c 1 {{ ubuntu_target_ip }}
      register: ping_result
      ignore_errors: yes
      changed_when: false
      
    - name: "📊 Resultado de conectividad"
      debug:
        msg: |
          {% if ping_result.rc == 0 %}
          ✅ Hay conectividad básica a Ubuntu Server
          🚀 Intentando configurar con Ansible...
          {% else %}
          ❌ No hay conectividad a Ubuntu Server  
          📝 Necesitas configuración de red primero
          {% endif %}
          
    - name: "🎯 Siguiente paso"
      debug:
        msg: |
          {% if ping_result.rc == 0 %}
          Ejecuta: ansible-playbook site.yml --ask-pass
          {% else %}
          Opciones:
          1. Configurar red manualmente en Ubuntu Server
          2. Conectarte a la red del laboratorio
          3. Pedir ayuda al administrador de la red
          {% endif %}