---
# =============================================================================
# SOLUCIÓN FINAL - Control via vSphere REST API
# =============================================================================

- hosts: localhost
  connection: local  
  gather_facts: no
  vars:
    ansible_become: false
    vcenter_host: "168.121.48.254"
    vcenter_port: 10123
    vcenter_user: "root"
    vcenter_pass: "qwe123$"
    
  tasks:
    - name: "🔑 Obtener token de autenticación vSphere"
      uri:
        url: "https://{{ vcenter_host }}:{{ vcenter_port }}/rest/com/vmware/cis/session"
        method: POST
        validate_certs: no
        force_basic_auth: yes
        url_username: "{{ vcenter_user }}"
        url_password: "{{ vcenter_pass }}"
        headers:
          Content-Type: "application/json"
      register: auth_result
      
    - name: "✅ Token obtenido"
      debug:
        msg: "Autenticación exitosa con vSphere API"
      when: auth_result.status == 200
      
    - name: "📋 Estrategia recomendada"
      debug:
        msg: |
          🎯 Ahora que confirmamos acceso a vSphere API, tenemos 2 opciones:
          
          ✅ OPCIÓN A: Configurar red manualmente UNA VEZ
          - Cambiar Ubuntu Server a tu red (192.168.0.48)
          - Después Ansible maneja TODO automáticamente
          
          ✅ OPCIÓN B: Usar vSphere API para ejecutar comandos  
          - Control completo via API de vCenter
          - Más complejo pero 100% automatizado
          
          🎓 RECOMENDACIÓN: Opción A (más simple y educativo)
          
          📝 PRÓXIMO PASO:
          1. Configurar red de Ubuntu Server una sola vez
          2. Ejecutar: ansible-playbook site.yml --ask-pass
          3. ¡Ansible hace todo el resto!