---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:
    - name: "Test vCenter conectividad"
      uri:
        url: "https://168.121.48.254:10123/ui/"
        method: GET
        validate_certs: no
        timeout: 10
      register: result
      
    - debug:
        msg: "vCenter responde: {{ result.status }}"